version: '3'
services:
  app:
    container_name: shopping-list
    restart: always
    build: .
    ports:
      - '5000:5000'
    links:
      - mongo
    environment:
      - NODE_ENV=production
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
